/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { QuickAnonymize$Params } from './fn/data-anonymization/quick-anonymize';
export { quickAnonymize } from './fn/data-anonymization/quick-anonymize';
export type { BatchAnonymize$Params } from './fn/data-anonymization/batch-anonymize';
export { batchAnonymize } from './fn/data-anonymization/batch-anonymize';
export type { AnonymizeData$Params } from './fn/data-anonymization/anonymize-data';
export { anonymizeData } from './fn/data-anonymization/anonymize-data';
export type { GetAvailableStrategies$Params } from './fn/data-anonymization/get-available-strategies';
export { getAvailableStrategies } from './fn/data-anonymization/get-available-strategies';
export type { HealthCheck$Params } from './fn/data-anonymization/health-check';
export { healthCheck } from './fn/data-anonymization/health-check';
