/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AnonymizationRequest } from './models/anonymization-request';
export type { AnonymizationResponse } from './models/anonymization-response';
