/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnonymizationRequest } from '../../models/anonymization-request';
import { AnonymizationResponse } from '../../models/anonymization-response';

export interface AnonymizeData$Params {
      body: AnonymizationRequest
}

export function anonymizeData(http: HttpClient, rootUrl: string, params: AnonymizeData$Params, context?: HttpContext): Observable<StrictHttpResponse<AnonymizationResponse>> {
  const rb = new RequestBuilder(rootUrl, anonymizeData.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AnonymizationResponse>;
    })
  );
}

anonymizeData.PATH = '/api/v1/anonymization/anonymize';
