/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AnonymizationResponse {
  anonymizedData?: {
[key: string]: {
};
};
  fieldsProcessed?: number;
  message?: string;
  strategy?: string;
  success?: boolean;
  timestamp?: string;
}
