/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Anonymization request containing data and strategy
 */
export interface AnonymizationRequest {
  data: {
[key: string]: {
};
};
  preserveFormat?: boolean;
  seed?: number;
  strategy: string;
}
